/**
 * Supabase에 주문 시스템 테이블 생성 스크립트
 */
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Supabase 환경 변수가 설정되지 않았습니다.');
  console.error('NEXT_PUBLIC_SUPABASE_URL과 NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY를 확인하세요.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function createOrderTables() {
  console.log('🚀 주문 시스템 테이블 생성 시작...\n');

  const migrationPath = path.join(
    process.cwd(),
    'supabase/migrations/20250002000000_create_order_system.sql'
  );

  // 마이그레이션 파일 읽기
  const sql = fs.readFileSync(migrationPath, 'utf-8');

  try {
    // SQL 실행
    const { error } = await supabase.rpc('exec_sql', { sql_query: sql });

    if (error) {
      console.error('❌ 테이블 생성 실패:', error);

      // 개별 테이블 생성 시도
      console.log('\n⚠️  개별 SQL 실행 시도 중...\n');
      await createTablesIndividually();
      return;
    }

    console.log('✅ 주문 시스템 테이블 생성 완료!');
    console.log('\n생성된 테이블:');
    console.log('  - orders (주문)');
    console.log('  - order_items (주문 상품)');
    console.log('  - payments (결제)');
    console.log('\n테이블 확인: Supabase Dashboard → Table Editor');
  } catch (err) {
    console.error('❌ 예외 발생:', err);
    console.log('\n⚠️  개별 SQL 실행 시도 중...\n');
    await createTablesIndividually();
  }
}

async function createTablesIndividually() {
  const queries = [
    {
      name: 'orders 테이블',
      sql: `
        CREATE TABLE IF NOT EXISTS public.orders (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_number VARCHAR(50) UNIQUE NOT NULL,
          customer_name VARCHAR(100) NOT NULL,
          customer_phone VARCHAR(20) NOT NULL,
          customer_email VARCHAR(255),
          total_amount INTEGER NOT NULL,
          discount_amount INTEGER DEFAULT 0 NOT NULL,
          final_amount INTEGER NOT NULL,
          status VARCHAR(50) NOT NULL DEFAULT 'pending',
          order_notes TEXT,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
          confirmed_at TIMESTAMP WITH TIME ZONE,
          completed_at TIMESTAMP WITH TIME ZONE
        );
      `,
    },
    {
      name: 'order_items 테이블',
      sql: `
        CREATE TABLE IF NOT EXISTS public.order_items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
          menu_id BIGINT NOT NULL REFERENCES public.menu(id),
          menu_name VARCHAR(255) NOT NULL,
          menu_price INTEGER NOT NULL,
          quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
          temperature VARCHAR(10),
          item_price INTEGER NOT NULL,
          item_total INTEGER NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        );
      `,
    },
    {
      name: 'payments 테이블',
      sql: `
        CREATE TABLE IF NOT EXISTS public.payments (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
          payment_method VARCHAR(50) NOT NULL,
          amount INTEGER NOT NULL,
          status VARCHAR(50) NOT NULL DEFAULT 'success',
          mock_transaction_id VARCHAR(100) NOT NULL,
          mock_approval_number VARCHAR(100),
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        );
      `,
    },
    {
      name: 'RLS 정책',
      sql: `
        ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS "orders_policy" ON public.orders;
        CREATE POLICY "orders_policy" ON public.orders FOR ALL TO public USING (true) WITH CHECK (true);

        DROP POLICY IF EXISTS "order_items_policy" ON public.order_items;
        CREATE POLICY "order_items_policy" ON public.order_items FOR ALL TO public USING (true) WITH CHECK (true);

        DROP POLICY IF EXISTS "payments_policy" ON public.payments;
        CREATE POLICY "payments_policy" ON public.payments FOR ALL TO public USING (true) WITH CHECK (true);
      `,
    },
  ];

  for (const query of queries) {
    try {
      const { error } = await supabase.rpc('exec_sql', { sql_query: query.sql });

      if (error) {
        console.error(`❌ ${query.name} 생성 실패:`, error.message);
      } else {
        console.log(`✅ ${query.name} 생성 완료`);
      }
    } catch (err) {
      console.error(`❌ ${query.name} 예외:`, err);
    }
  }

  console.log('\n⚠️  일부 테이블 생성이 실패했을 수 있습니다.');
  console.log('Supabase Dashboard → SQL Editor에서 수동으로 실행해주세요.');
}

createOrderTables();
