-- =====================================================
-- 카테고리 테이블 생성
-- =====================================================
-- 메뉴 카테고리 관리 (커피, 디저트, 음료, 푸드 등)

CREATE TABLE IF NOT EXISTS public.category (
  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_by varchar(255) NOT NULL,
  created_date timestamp(6) NOT NULL,
  updated_by varchar(255) NULL,
  updated_date timestamp(6) NULL,
  name varchar(255) NOT NULL,
  order_no int4 NOT NULL,
  status varchar(255) NOT NULL,

  CONSTRAINT category_pkey PRIMARY KEY (id)
);

-- =====================================================
-- 인덱스 생성 (성능 최적화)
-- =====================================================

-- 정렬 순서 기반 카테고리 조회 최적화
CREATE INDEX IF NOT EXISTS idx_category_order_no
ON public.category USING btree (order_no);

-- =====================================================
-- 테이블 코멘트
-- =====================================================

COMMENT ON TABLE public.category IS '메뉴 카테고리 테이블 - 커피, 디저트, 음료, 푸드 등 분류';
COMMENT ON COLUMN public.category.id IS '카테고리 ID (PK, auto increment)';
COMMENT ON COLUMN public.category.name IS '카테고리 이름 (예: 커피, 디저트)';
COMMENT ON COLUMN public.category.order_no IS '정렬 순서 (화면 표시 순서)';
COMMENT ON COLUMN public.category.status IS '카테고리 상태 (common_code.id 참조)';
