-- =====================================================
-- 메뉴 아이템 테이블 생성
-- =====================================================
-- 커피, 디저트, 음료 등 판매 메뉴 관리

CREATE TABLE IF NOT EXISTS public.menu (
  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_by varchar(255) NOT NULL,
  created_date timestamp(6) NOT NULL,
  updated_by varchar(255) NULL,
  updated_date timestamp(6) NULL,
  cold bool NOT NULL,
  description varchar(500) NOT NULL,
  discount_price int4 NULL,
  hot bool NOT NULL,
  marketing _text NULL,
  name varchar(255) NOT NULL,
  order_no int4 NOT NULL,
  price int4 NOT NULL,
  status varchar(255) NOT NULL,
  category_id int8 NULL,

  CONSTRAINT menu_pkey PRIMARY KEY (id),
  CONSTRAINT fkww84tou7nixng06lmxawvcre FOREIGN KEY (category_id) REFERENCES public.category(id)
);

-- =====================================================
-- 인덱스 생성 (성능 최적화)
-- =====================================================

-- 카테고리별 메뉴 조회 최적화
CREATE INDEX IF NOT EXISTS idx_menu_category_id
ON public.menu USING btree (category_id);

-- 정렬 순서 기반 메뉴 조회 최적화
CREATE INDEX IF NOT EXISTS idx_menu_order_no
ON public.menu USING btree (order_no);

-- 상태별 메뉴 필터링 최적화
CREATE INDEX IF NOT EXISTS idx_menu_status
ON public.menu USING btree (status);

-- 복합 인덱스: 카테고리 + 상태 + 정렬 순서
CREATE INDEX IF NOT EXISTS idx_menu_category_status_order
ON public.menu USING btree (category_id, status, order_no);

-- =====================================================
-- 테이블 코멘트
-- =====================================================

COMMENT ON TABLE public.menu IS '메뉴 아이템 테이블 - 판매 상품 정보 관리';
COMMENT ON COLUMN public.menu.id IS '메뉴 ID (PK, auto increment)';
COMMENT ON COLUMN public.menu.name IS '메뉴 이름 (예: 아메리카노)';
COMMENT ON COLUMN public.menu.description IS '메뉴 설명 (최대 500자)';
COMMENT ON COLUMN public.menu.price IS '기본 가격 (원 단위)';
COMMENT ON COLUMN public.menu.discount_price IS '할인 가격 (원 단위, nullable)';
COMMENT ON COLUMN public.menu.cold IS '차가운 음료 제공 여부';
COMMENT ON COLUMN public.menu.hot IS '따뜻한 음료 제공 여부';
COMMENT ON COLUMN public.menu.status IS '메뉴 상태 (common_code.id 참조: 판매중, 품절 등)';
COMMENT ON COLUMN public.menu.marketing IS '마케팅 태그 배열 (common_code.id 참조: 인기, 신메뉴 등)';
COMMENT ON COLUMN public.menu.category_id IS '카테고리 FK (category 테이블 참조)';
COMMENT ON COLUMN public.menu.order_no IS '정렬 순서 (화면 표시 순서)';
