-- =============================================
-- MVP 모의 결제 시스템 마이그레이션
-- 주문, 주문 항목, 결제 테이블 생성
-- =============================================

-- =============================================
-- 1. orders 테이블 (주문)
-- =============================================
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 주문 번호 (사용자 노출용, 예: ORD20250128001)
  order_number VARCHAR(50) UNIQUE NOT NULL,

  -- 주문자 정보 (MVP: 인증 없이 입력받음)
  customer_name VARCHAR(100) NOT NULL,
  customer_phone VARCHAR(20) NOT NULL,
  customer_email VARCHAR(255),

  -- 주문 금액
  total_amount INTEGER NOT NULL,
  discount_amount INTEGER DEFAULT 0 NOT NULL,
  final_amount INTEGER NOT NULL,

  -- 주문 상태
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  -- pending: 주문 생성
  -- paid: 결제 완료
  -- confirmed: 주문 확인
  -- completed: 완료
  -- cancelled: 취소

  -- 메모
  order_notes TEXT,

  -- 타임스탬프
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  confirmed_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE
);

-- orders 인덱스
CREATE INDEX idx_orders_order_number ON public.orders(order_number);
CREATE INDEX idx_orders_customer_phone ON public.orders(customer_phone);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_created_at ON public.orders(created_at DESC);

-- orders 코멘트
COMMENT ON TABLE public.orders IS 'MVP 주문 테이블';
COMMENT ON COLUMN public.orders.order_number IS '사용자 노출용 주문 번호 (예: ORD20250128001)';
COMMENT ON COLUMN public.orders.status IS '주문 상태: pending(생성), paid(결제완료), confirmed(확인), completed(완료), cancelled(취소)';

-- =============================================
-- 2. order_items 테이블 (주문 상세 항목)
-- =============================================
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 주문 FK
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,

  -- 메뉴 FK
  menu_id BIGINT NOT NULL REFERENCES public.menu(id),

  -- 주문 당시 메뉴 정보 (스냅샷 - 메뉴 가격 변경 대비)
  menu_name VARCHAR(255) NOT NULL,
  menu_price INTEGER NOT NULL,

  -- 수량 및 옵션
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  temperature VARCHAR(10), -- 'hot' or 'cold'

  -- 항목별 금액
  item_price INTEGER NOT NULL,
  item_total INTEGER NOT NULL,

  -- 타임스탬프
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- order_items 인덱스
CREATE INDEX idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX idx_order_items_menu_id ON public.order_items(menu_id);

-- order_items 코멘트
COMMENT ON TABLE public.order_items IS 'MVP 주문 상세 항목 테이블';
COMMENT ON COLUMN public.order_items.menu_name IS '주문 당시 메뉴명 (스냅샷)';
COMMENT ON COLUMN public.order_items.menu_price IS '주문 당시 메뉴 가격 (스냅샷)';
COMMENT ON COLUMN public.order_items.temperature IS '음료 온도: hot 또는 cold';

-- =============================================
-- 3. payments 테이블 (결제 정보)
-- =============================================
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 주문 FK
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,

  -- 결제 방법
  payment_method VARCHAR(50) NOT NULL,
  -- 'card': 신용카드
  -- 'kakao': 카카오페이
  -- 'naver': 네이버페이
  -- 'cash': 현장결제

  -- 결제 금액
  amount INTEGER NOT NULL,

  -- 결제 상태 (MVP: 항상 'success')
  status VARCHAR(50) NOT NULL DEFAULT 'success',
  -- success: 성공
  -- pending: 대기
  -- failed: 실패

  -- 모의 결제 정보
  mock_transaction_id VARCHAR(100) NOT NULL,
  mock_approval_number VARCHAR(100),

  -- 타임스탬프
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- payments 인덱스
CREATE INDEX idx_payments_order_id ON public.payments(order_id);
CREATE INDEX idx_payments_status ON public.payments(status);
CREATE INDEX idx_payments_created_at ON public.payments(created_at DESC);
CREATE INDEX idx_payments_transaction_id ON public.payments(mock_transaction_id);

-- payments 코멘트
COMMENT ON TABLE public.payments IS 'MVP 모의 결제 정보 테이블';
COMMENT ON COLUMN public.payments.payment_method IS '결제 방법: card(신용카드), kakao(카카오페이), naver(네이버페이), cash(현장결제)';
COMMENT ON COLUMN public.payments.status IS 'MVP에서는 항상 success';
COMMENT ON COLUMN public.payments.mock_transaction_id IS '모의 트랜잭션 ID';
COMMENT ON COLUMN public.payments.mock_approval_number IS '모의 승인 번호';

-- =============================================
-- 4. RLS (Row Level Security) 정책 설정
-- =============================================

-- orders 테이블 RLS 활성화
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- orders 읽기 정책: 모든 사용자 허용
CREATE POLICY "orders_select_policy"
ON public.orders FOR SELECT
TO public
USING (true);

-- orders 쓰기 정책: 인증된 사용자만 (향후 확장 대비)
CREATE POLICY "orders_insert_policy"
ON public.orders FOR INSERT
TO public
WITH CHECK (true);

-- orders 업데이트 정책: 인증된 사용자만
CREATE POLICY "orders_update_policy"
ON public.orders FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- order_items 테이블 RLS 활성화
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- order_items 읽기 정책: 모든 사용자 허용
CREATE POLICY "order_items_select_policy"
ON public.order_items FOR SELECT
TO public
USING (true);

-- order_items 쓰기 정책: 모든 사용자 허용 (MVP)
CREATE POLICY "order_items_insert_policy"
ON public.order_items FOR INSERT
TO public
WITH CHECK (true);

-- payments 테이블 RLS 활성화
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- payments 읽기 정책: 모든 사용자 허용
CREATE POLICY "payments_select_policy"
ON public.payments FOR SELECT
TO public
USING (true);

-- payments 쓰기 정책: 모든 사용자 허용 (MVP)
CREATE POLICY "payments_insert_policy"
ON public.payments FOR INSERT
TO public
WITH CHECK (true);

-- payments 업데이트 정책: 모든 사용자 허용 (MVP)
CREATE POLICY "payments_update_policy"
ON public.payments FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- =============================================
-- 5. 트리거: updated_at 자동 업데이트
-- =============================================

-- orders updated_at 트리거
CREATE OR REPLACE FUNCTION update_orders_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_orders_updated_at
BEFORE UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION update_orders_updated_at();

-- payments updated_at 트리거
CREATE OR REPLACE FUNCTION update_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_payments_updated_at
BEFORE UPDATE ON public.payments
FOR EACH ROW
EXECUTE FUNCTION update_payments_updated_at();

-- =============================================
-- 마이그레이션 완료
-- =============================================
