-- =====================================================
-- 매장 테이블 생성 마이그레이션
-- 생성일: 2025-01-12
-- 설명: 커피 매장 정보를 저장하는 테이블 생성 및 RLS 정책 설정
-- =====================================================

-- 1. 매장 테이블 생성 (BIGINT ID)
CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  address VARCHAR(500),
  phone VARCHAR(20),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  image_url TEXT,
  thumbnail_url TEXT,
  opening_hours JSONB,
  has_coupon BOOLEAN DEFAULT false NOT NULL,
  has_stamp BOOLEAN DEFAULT false NOT NULL,
  like_count INTEGER DEFAULT 0 NOT NULL,
  comment_count INTEGER DEFAULT 0 NOT NULL,
  order_count INTEGER DEFAULT 0 NOT NULL,
  status VARCHAR(20) DEFAULT 'active' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,

  -- 제약 조건
  CONSTRAINT stores_status_check CHECK (status IN ('active', 'inactive', 'closed')),
  CONSTRAINT stores_like_count_check CHECK (like_count >= 0),
  CONSTRAINT stores_comment_count_check CHECK (comment_count >= 0),
  CONSTRAINT stores_order_count_check CHECK (order_count >= 0)
);

-- 2. 인덱스 생성 (쿼리 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_stores_status ON public.stores(status);
CREATE INDEX IF NOT EXISTS idx_stores_location ON public.stores(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_stores_created_at ON public.stores(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stores_order_count ON public.stores(order_count DESC);
CREATE INDEX IF NOT EXISTS idx_stores_name_search ON public.stores USING gin(to_tsvector('simple', name));

-- 3. updated_at 자동 업데이트 트리거 함수 생성
CREATE OR REPLACE FUNCTION update_stores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. 트리거 생성
DROP TRIGGER IF EXISTS update_stores_updated_at ON public.stores;
CREATE TRIGGER update_stores_updated_at
  BEFORE UPDATE ON public.stores
  FOR EACH ROW
  EXECUTE FUNCTION update_stores_updated_at();

-- 5. RLS (Row Level Security) 활성화
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

-- 6. RLS 정책 생성
-- 모든 사용자가 활성 상태의 매장을 조회할 수 있도록 허용
DROP POLICY IF EXISTS "stores_select_policy" ON public.stores;
CREATE POLICY "stores_select_policy"
  ON public.stores
  FOR SELECT
  TO public
  USING (status = 'active');

-- 7. 샘플 데이터 삽입
INSERT INTO public.stores (
  name,
  description,
  address,
  phone,
  latitude,
  longitude,
  has_coupon,
  has_stamp,
  like_count,
  comment_count,
  order_count,
  opening_hours,
  status
) VALUES
  (
    '동대문종합시장 1호점',
    '신선한 원두로 만드는 정통 커피 전문점. 아메리카노, 라떼, 디저트 등 다양한 메뉴 제공.',
    '서울특별시 동대문구 종합시장로 123',
    '02-1234-5678',
    37.5710,
    127.0094,
    true,
    true,
    28,
    16,
    34,
    '{"monday": "08:00-22:00", "tuesday": "08:00-22:00", "wednesday": "08:00-22:00", "thursday": "08:00-22:00", "friday": "08:00-23:00", "saturday": "09:00-23:00", "sunday": "09:00-21:00"}'::jsonb,
    'active'
  ),
  (
    '강남 카페거리점',
    '프리미엄 원두만을 사용하는 고급 카페. 조용한 분위기와 쾌적한 공간.',
    '서울특별시 강남구 테헤란로 456',
    '02-2345-6789',
    37.4979,
    127.0276,
    true,
    false,
    45,
    23,
    67,
    '{"monday": "07:00-22:00", "tuesday": "07:00-22:00", "wednesday": "07:00-22:00", "thursday": "07:00-22:00", "friday": "07:00-24:00", "saturday": "08:00-24:00", "sunday": "08:00-22:00"}'::jsonb,
    'active'
  ),
  (
    '홍대 문화점',
    '젊음과 감성이 가득한 핫플레이스. SNS 인증샷 필수 카페.',
    '서울특별시 마포구 홍익로 789',
    '02-3456-7890',
    37.5563,
    126.9236,
    false,
    true,
    32,
    18,
    41,
    '{"monday": "10:00-23:00", "tuesday": "10:00-23:00", "wednesday": "10:00-23:00", "thursday": "10:00-24:00", "friday": "10:00-02:00", "saturday": "10:00-02:00", "sunday": "10:00-23:00"}'::jsonb,
    'active'
  ),
  (
    '이태원 글로벌점',
    '세계 각국의 스페셜티 커피를 맛볼 수 있는 특별한 공간.',
    '서울특별시 용산구 이태원로 234',
    '02-4567-8901',
    37.5345,
    126.9944,
    true,
    true,
    56,
    31,
    89,
    '{"monday": "08:00-22:00", "tuesday": "08:00-22:00", "wednesday": "08:00-22:00", "thursday": "08:00-23:00", "friday": "08:00-24:00", "saturday": "09:00-24:00", "sunday": "09:00-22:00"}'::jsonb,
    'active'
  ),
  (
    '신촌 대학점',
    '학생들의 스터디 카페. 넓은 공간과 무료 와이파이 제공.',
    '서울특별시 서대문구 신촌로 567',
    '02-5678-9012',
    37.5590,
    126.9389,
    false,
    false,
    21,
    12,
    28,
    '{"monday": "07:00-24:00", "tuesday": "07:00-24:00", "wednesday": "07:00-24:00", "thursday": "07:00-24:00", "friday": "07:00-24:00", "saturday": "09:00-24:00", "sunday": "09:00-23:00"}'::jsonb,
    'active'
  );

-- 8. 코멘트 추가 (테이블 및 컬럼 설명)
COMMENT ON TABLE public.stores IS '커피 매장 정보 테이블';
COMMENT ON COLUMN public.stores.id IS '매장 고유 ID (BIGINT)';
COMMENT ON COLUMN public.stores.name IS '매장 이름';
COMMENT ON COLUMN public.stores.description IS '매장 설명';
COMMENT ON COLUMN public.stores.address IS '매장 주소';
COMMENT ON COLUMN public.stores.phone IS '매장 전화번호';
COMMENT ON COLUMN public.stores.latitude IS '위도 (Decimal 10,8)';
COMMENT ON COLUMN public.stores.longitude IS '경도 (Decimal 11,8)';
COMMENT ON COLUMN public.stores.image_url IS '매장 대표 이미지 URL';
COMMENT ON COLUMN public.stores.thumbnail_url IS '매장 썸네일 이미지 URL';
COMMENT ON COLUMN public.stores.opening_hours IS '영업 시간 (JSONB 형식)';
COMMENT ON COLUMN public.stores.has_coupon IS '쿠폰 제공 여부';
COMMENT ON COLUMN public.stores.has_stamp IS '스탬프 제공 여부';
COMMENT ON COLUMN public.stores.like_count IS '좋아요 수';
COMMENT ON COLUMN public.stores.comment_count IS '댓글 수';
COMMENT ON COLUMN public.stores.order_count IS '주문 수';
COMMENT ON COLUMN public.stores.status IS '매장 상태 (active, inactive, closed)';
COMMENT ON COLUMN public.stores.created_at IS '생성 일시';
COMMENT ON COLUMN public.stores.updated_at IS '수정 일시 (자동 업데이트)';
