-- =====================================================
-- 매장별 메뉴 테이블 생성 마이그레이션
-- 생성일: 2025-01-13
-- 설명: 매장과 메뉴의 1:N 관계를 관리하는 테이블 생성
-- =====================================================

-- 1. 매장별 메뉴 테이블 생성
CREATE TABLE IF NOT EXISTS public.store_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  menu_id BIGINT NOT NULL REFERENCES public.menu(id) ON DELETE CASCADE,
  is_available BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,

  -- 제약 조건: 같은 매장에 같은 메뉴는 중복 불가
  CONSTRAINT store_menu_unique UNIQUE (store_id, menu_id)
);

-- 2. 인덱스 생성 (쿼리 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_store_menu_store_id ON public.store_menu(store_id);
CREATE INDEX IF NOT EXISTS idx_store_menu_menu_id ON public.store_menu(menu_id);
CREATE INDEX IF NOT EXISTS idx_store_menu_is_available ON public.store_menu(is_available);
CREATE INDEX IF NOT EXISTS idx_store_menu_store_available ON public.store_menu(store_id, is_available);

-- 3. updated_at 자동 업데이트 트리거 함수 생성
CREATE OR REPLACE FUNCTION update_store_menu_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. 트리거 생성
DROP TRIGGER IF EXISTS update_store_menu_updated_at ON public.store_menu;
CREATE TRIGGER update_store_menu_updated_at
  BEFORE UPDATE ON public.store_menu
  FOR EACH ROW
  EXECUTE FUNCTION update_store_menu_updated_at();

-- 5. RLS (Row Level Security) 활성화
ALTER TABLE public.store_menu ENABLE ROW LEVEL SECURITY;

-- 6. RLS 정책 생성
-- 모든 사용자가 활성 상태의 매장 메뉴를 조회할 수 있도록 허용
DROP POLICY IF EXISTS "store_menu_select_policy" ON public.store_menu;
CREATE POLICY "store_menu_select_policy"
  ON public.store_menu
  FOR SELECT
  TO public
  USING (
    is_available = true AND
    EXISTS (
      SELECT 1 FROM public.stores
      WHERE stores.id = store_menu.store_id
      AND stores.status = 'active'
    )
  );

-- 7. 각 매장에 대표 메뉴 10개씩 추가
-- 매장 1: 메뉴 ID 151~160 (클래식 아메리카노 & 라떼 라인업)
-- 매장 2: 메뉴 ID 154, 155, 156, 161~167 (프리미엄 커피 & 시그니처 메뉴)
-- 매장 3: 메뉴 ID 157, 158, 159, 168~174 (시그니처 & 스무디 라인업)
-- 매장 4: 메뉴 ID 160, 161, 162, 175~181 (프라페 & 스페셜 커피 라인업)
-- 매장 5: 메뉴 ID 163, 164, 165, 182~188 (논커피 & 티 라인업)
INSERT INTO public.store_menu (store_id, menu_id, is_available)
VALUES
  -- 매장 1 (동대문종합시장 1호점) - ID 1
  (1, 151, true),
  (1, 152, true),
  (1, 153, true),
  (1, 154, true),
  (1, 155, true),
  (1, 156, true),
  (1, 157, true),
  (1, 158, true),
  (1, 159, true),
  (1, 160, true),
  -- 매장 2 (강남 카페거리점) - ID 2
  (2, 154, true),
  (2, 155, true),
  (2, 156, true),
  (2, 161, true),
  (2, 162, true),
  (2, 163, true),
  (2, 164, true),
  (2, 165, true),
  (2, 166, true),
  (2, 167, true),
  -- 매장 3 (홍대 문화점) - ID 3
  (3, 157, true),
  (3, 158, true),
  (3, 159, true),
  (3, 168, true),
  (3, 169, true),
  (3, 170, true),
  (3, 171, true),
  (3, 172, true),
  (3, 173, true),
  (3, 174, true),
  -- 매장 4 (이태원 글로벌점) - ID 4
  (4, 160, true),
  (4, 161, true),
  (4, 162, true),
  (4, 175, true),
  (4, 176, true),
  (4, 177, true),
  (4, 178, true),
  (4, 179, true),
  (4, 180, true),
  (4, 181, true),
  -- 매장 5 (신촌 대학점) - ID 5
  (5, 163, true),
  (5, 164, true),
  (5, 165, true),
  (5, 182, true),
  (5, 183, true),
  (5, 184, true),
  (5, 185, true),
  (5, 186, true),
  (5, 187, true),
  (5, 188, true)
ON CONFLICT (store_id, menu_id) DO NOTHING;

-- 8. 코멘트 추가 (테이블 및 컬럼 설명)
COMMENT ON TABLE public.store_menu IS '매장별 메뉴 테이블 - 매장과 메뉴의 1:N 관계 관리';
COMMENT ON COLUMN public.store_menu.id IS '매장 메뉴 고유 ID (BIGINT)';
COMMENT ON COLUMN public.store_menu.store_id IS '매장 ID (stores 테이블 참조)';
COMMENT ON COLUMN public.store_menu.menu_id IS '메뉴 ID (menu 테이블 참조)';
COMMENT ON COLUMN public.store_menu.is_available IS '메뉴 판매 가능 여부';
COMMENT ON COLUMN public.store_menu.created_at IS '생성 일시';
COMMENT ON COLUMN public.store_menu.updated_at IS '수정 일시 (자동 업데이트)';

